### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1000000000",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1000000000",
  "amount" : 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "0bea525b809b467889e6a5f7bc848cf9",
  "accountNumber" : "1000000000",
  "amount" : 100
}

### query transaction
GET http://localhost:8080/transaction/6f87cb8e44ce47149ee36b15d637bc67